name: tmsdiff
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
prefix: !!python/unicode '/Users/samtarakajian/miniconda2/envs/tmsdiff'

